export const noob = {
    'interceptor': false,
    'status': '0',
    'message': null,
    'body': {
        'totalProductos': 29,
        'productos': [
            {
                'product_category_id': 1,
                'product_city_id': 1,
                'product_city_name': 'Medellin',
                'product_country_id': 1,
                'product_currency': 'COP',
                'product_id': 7427,
                'product_is_low_price': false,
                'product_name': 'Versys De Sqa2',
                'product_old_price': 1000,
                'product_price': 1000,
                'product_sell_type': 'VENTA',
                'product_state_id': 1,
                'product_state_name': 'Antioquia',
                'product_status': 'active',
                'product_subcategory_id': 18,
                'product_used': false,
                'product_visible': true,
                'product_published_at': '2019-04-08T22:31:30.510+0000',
                'seller_community_id': 5,
                'seller_community_name': 'SQA',
                'seller_company_name': 'SQA',
                'seller_name': 'Deisy Marin',
                'product_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12527/1554762679736-14123-versys650sergio.jpg',
                'seller_photo_url': null,
                'product_previous_price': null,
                'seller_company_color': '#2E2EFE',
                'product_manual_feature': null
            },
            {
                'product_category_id': 1,
                'product_city_id': 1,
                'product_city_name': 'Medellin',
                'product_country_id': 1,
                'product_currency': 'COP',
                'product_id': 7419,
                'product_is_low_price': false,
                'product_name': 'Prueba',
                'product_old_price': 10000000,
                'product_price': 10000000,
                'product_sell_type': 'VENTA',
                'product_state_id': 1,
                'product_state_name': 'Antioquia',
                'product_status': 'active',
                'product_subcategory_id': 19,
                'product_used': false,
                'product_visible': true,
                'product_published_at': '2019-04-03T15:37:28.432+0000',
                'seller_community_id': 2,
                'seller_community_name': 'Pragma',
                'seller_company_name': 'Pragma',
                'seller_name': 'Boris Velez 00',
                'product_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12518/1554305722923-14132-Jose_pasillas.jpg',
                'seller_photo_url': null,
                'product_previous_price': null,
                'seller_company_color': '#FE782E',
                'product_manual_feature': null
            },
            {
                'product_category_id': 1,
                'product_city_id': 1,
                'product_city_name': 'Medellin',
                'product_country_id': 1,
                'product_currency': 'COP',
                'product_id': 7380,
                'product_is_low_price': false,
                'product_name': 'No Hacer Nada Con Este Producto!',
                'product_old_price': 2000,
                'product_price': 2100,
                'product_sell_type': 'SUBASTA',
                'product_state_id': 1,
                'product_state_name': 'Antioquia',
                'product_status': 'active',
                'product_subcategory_id': 18,
                'product_used': false,
                'product_visible': false,
                'product_published_at': '2019-04-01T14:43:41.920+0000',
                'seller_community_id': 2,
                'seller_community_name': 'Pragma',
                'seller_company_name': 'Pragma',
                'seller_name': 'Boris Velez 00',
                'product_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12462/1554129754779-3172-versys650sergio.jpg',
                'seller_photo_url': null,
                'product_previous_price': null,
                'seller_company_color': '#FE782E',
                'product_manual_feature': null
            },
            {
                'product_category_id': 1,
                'product_city_id': 19,
                'product_city_name': 'Bello',
                'product_country_id': 1,
                'product_currency': 'COP',
                'product_id': 7349,
                'product_is_low_price': false,
                'product_name': 'Colección Deportes ABa',
                'product_old_price': 607754,
                'product_price': 323223232323,
                'product_sell_type': 'SUBASTA',
                'product_state_id': 1,
                'product_state_name': 'Antioquia',
                'product_status': 'active',
                'product_subcategory_id': 20,
                'product_used': false,
                'product_visible': true,
                'product_published_at': '2019-03-06T13:20:06.681+0000',
                'seller_community_id': 5,
                'seller_community_name': 'SQA',
                'seller_company_name': 'SQA',
                'seller_name': 'Diego Alexander Sierra ',
                'product_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12358/2014-regaliz-coleccion-vintage-deportes-II.jpg',
                'seller_photo_url': null,
                'product_previous_price': null,
                'seller_company_color': '#2E2EFE',
                'product_manual_feature': null
            },
            {
                'product_category_id': 1,
                'product_city_id': 19,
                'product_city_name': 'Bello',
                'product_country_id': 1,
                'product_currency': 'COP',
                'product_id': 7287,
                'product_is_low_price': false,
                'product_name': 'Colección Deportes',
                'product_old_price': 500000,
                'product_price': 555000,
                'product_sell_type': 'SUBASTA',
                'product_state_id': 1,
                'product_state_name': 'Antioquia',
                'product_status': 'active',
                'product_subcategory_id': 20,
                'product_used': false,
                'product_visible': true,
                'product_published_at': '2019-03-06T13:19:50.861+0000',
                'seller_community_id': 5,
                'seller_community_name': 'SQA',
                'seller_company_name': 'SQA',
                'seller_name': 'Diego Alexander Sierra ',
                'product_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/11074/2014-regaliz-coleccion-vintage-deportes-II.jpg',
                'seller_photo_url': null,
                'product_previous_price': null,
                'seller_company_color': '#2E2EFE',
                'product_manual_feature': null
            },
            {
                'product_category_id': 1,
                'product_city_id': 19,
                'product_city_name': 'Bello',
                'product_country_id': 1,
                'product_currency': 'COP',
                'product_id': 7251,
                'product_is_low_price': false,
                'product_name': 'Colección Deportes ABa',
                'product_old_price': 607754,
                'product_price': 551250,
                'product_sell_type': 'SUBASTA',
                'product_state_id': 1,
                'product_state_name': 'Antioquia',
                'product_status': 'active',
                'product_subcategory_id': 20,
                'product_used': false,
                'product_visible': true,
                'product_published_at': '2019-02-26T13:59:30.235+0000',
                'seller_community_id': 5,
                'seller_community_name': 'SQA',
                'seller_company_name': 'SQA',
                'seller_name': 'Diego Alexander Sierra ',
                'product_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/11002/2014-regaliz-coleccion-vintage-deportes-II.jpg',
                'seller_photo_url': null,
                'product_previous_price': 607754,
                'seller_company_color': '#2E2EFE',
                'product_manual_feature': null
            },
            {
                'product_category_id': 1,
                'product_city_id': 19,
                'product_city_name': 'Bello',
                'product_country_id': 1,
                'product_currency': 'COP',
                'product_id': 7236,
                'product_is_low_price': false,
                'product_name': 'Patines Negros',
                'product_old_price': 190000,
                'product_price': 190000,
                'product_sell_type': 'VENTA',
                'product_state_id': 1,
                'product_state_name': 'Antioquia',
                'product_status': 'active',
                'product_subcategory_id': 21,
                'product_used': false,
                'product_visible': true,
                'product_published_at': '2019-02-20T14:18:47.547+0000',
                'seller_community_id': 5,
                'seller_community_name': 'SQA',
                'seller_company_name': 'SQA',
                'seller_name': 'Diego Alexander Sierra ',
                'product_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/10987/Patines03.jpg',
                'seller_photo_url': null,
                'product_previous_price': null,
                'seller_company_color': '#2E2EFE',
                'product_manual_feature': null
            },
            {
                'product_category_id': 1,
                'product_city_id': 19,
                'product_city_name': 'Bello',
                'product_country_id': 1,
                'product_currency': 'COP',
                'product_id': 7235,
                'product_is_low_price': true,
                'product_name': 'Patines Rosados',
                'product_old_price': 90000,
                'product_price': 90000,
                'product_sell_type': 'VENTA',
                'product_state_id': 1,
                'product_state_name': 'Antioquia',
                'product_status': 'active',
                'product_subcategory_id': 21,
                'product_used': true,
                'product_visible': true,
                'product_published_at': '2019-02-20T14:18:42.351+0000',
                'seller_community_id': 5,
                'seller_community_name': 'SQA',
                'seller_company_name': 'SQA',
                'seller_name': 'Diego Alexander Sierra ',
                'product_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/10986/Patines01.jpg',
                'seller_photo_url': null,
                'product_previous_price': null,
                'seller_company_color': '#2E2EFE',
                'product_manual_feature': null
            },
            {
                'product_category_id': 1,
                'product_city_id': 19,
                'product_city_name': 'Bello',
                'product_country_id': 1,
                'product_currency': 'COP',
                'product_id': 7237,
                'product_is_low_price': false,
                'product_name': 'Patines Naranja',
                'product_old_price': 170000,
                'product_price': 170000,
                'product_sell_type': 'VENTA',
                'product_state_id': 1,
                'product_state_name': 'Antioquia',
                'product_status': 'active',
                'product_subcategory_id': 21,
                'product_used': false,
                'product_visible': true,
                'product_published_at': '2019-02-20T14:16:47.769+0000',
                'seller_community_id': 5,
                'seller_community_name': 'SQA',
                'seller_company_name': 'SQA',
                'seller_name': 'Diego Alexander Sierra ',
                'product_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/10988/Patines04.jpg',
                'seller_photo_url': null,
                'product_previous_price': null,
                'seller_company_color': '#2E2EFE',
                'product_manual_feature': null
            },
            {
                'product_category_id': 1,
                'product_city_id': 19,
                'product_city_name': 'Bello',
                'product_country_id': 1,
                'product_currency': 'COP',
                'product_id': 7239,
                'product_is_low_price': false,
                'product_name': 'Patines Rojos',
                'product_old_price': 165000,
                'product_price': 165000,
                'product_sell_type': 'VENTA',
                'product_state_id': 1,
                'product_state_name': 'Antioquia',
                'product_status': 'active',
                'product_subcategory_id': 21,
                'product_used': false,
                'product_visible': true,
                'product_published_at': '2019-02-20T14:16:32.834+0000',
                'seller_community_id': 5,
                'seller_community_name': 'SQA',
                'seller_company_name': 'SQA',
                'seller_name': 'Diego Alexander Sierra ',
                'product_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/10990/Patines06.jpg',
                'seller_photo_url': null,
                'product_previous_price': null,
                'seller_company_color': '#2E2EFE',
                'product_manual_feature': null
            },
            {
                'product_category_id': 1,
                'product_city_id': 1052,
                'product_city_name': 'Tarapaca',
                'product_country_id': 1,
                'product_currency': 'COP',
                'product_id': 7425,
                'product_is_low_price': false,
                'product_name': 'Casa De Playa - Sqa',
                'product_old_price': 250000,
                'product_price': 250000,
                'product_sell_type': 'ALQUILA',
                'product_state_id': 29,
                'product_state_name': 'Amazonas',
                'product_status': 'active',
                'product_subcategory_id': 21,
                'product_used': false,
                'product_visible': true,
                'product_published_at': '2019-04-04T19:19:32.855+0000',
                'seller_community_id': 5,
                'seller_community_name': 'SQA',
                'seller_company_name': 'SQA',
                'seller_name': 'Esteffany Garces',
                'product_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12524/1554405445024-14172-una-casa-en-la-playa-portuguesa_ampliacion.jpg',
                'seller_photo_url': null,
                'product_previous_price': null,
                'seller_company_color': '#2E2EFE',
                'product_manual_feature': null
            },
            {
                'product_category_id': 1,
                'product_city_id': 623,
                'product_city_name': 'San Juan Del Cesar',
                'product_country_id': 1,
                'product_currency': 'COP',
                'product_id': 7334,
                'product_is_low_price': false,
                'product_name': 'Funko Pop Anime One Punch Man-Saitama Toy',
                'product_old_price': 50000,
                'product_price': 50000,
                'product_sell_type': 'VENTA',
                'product_state_id': 14,
                'product_state_name': 'La Guajira',
                'product_status': 'active',
                'product_subcategory_id': 20,
                'product_used': false,
                'product_visible': true,
                'product_published_at': '2019-02-26T18:35:41.758+0000',
                'seller_community_id': 2,
                'seller_community_name': 'Pragma',
                'seller_company_name': 'Pragma',
                'seller_name': 'Jairo Vendoo',
                'product_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12318/1551206148181-14128-Saitama.jpg',
                'seller_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12459/1553891500908-3930-cidade-de-papel.jpg',
                'product_previous_price': null,
                'seller_company_color': '#FE782E',
                'product_manual_feature': null
            },
            {
                'product_category_id': 1,
                'product_city_id': 624,
                'product_city_name': 'Uribia',
                'product_country_id': 1,
                'product_currency': 'COP',
                'product_id': 7332,
                'product_is_low_price': false,
                'product_name': 'Funko Pop  One Piece - Donquixote Doflamingo',
                'product_old_price': 50000,
                'product_price': 50000,
                'product_sell_type': 'VENTA',
                'product_state_id': 14,
                'product_state_name': 'La Guajira',
                'product_status': 'active',
                'product_subcategory_id': 20,
                'product_used': false,
                'product_visible': true,
                'product_published_at': '2019-02-26T14:23:14.211+0000',
                'seller_community_id': 2,
                'seller_community_name': 'Pragma',
                'seller_company_name': 'Pragma',
                'seller_name': 'Jairo Vendoo',
                'product_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12316/1551191041159-14127-Doflamingo.jpg',
                'seller_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12459/1553891500908-3930-cidade-de-papel.jpg',
                'product_previous_price': null,
                'seller_company_color': '#FE782E',
                'product_manual_feature': null
            },
            {
                'product_category_id': 1,
                'product_city_id': 624,
                'product_city_name': 'Uribia',
                'product_country_id': 1,
                'product_currency': 'COP',
                'product_id': 7331,
                'product_is_low_price': false,
                'product_name': 'Funko Pop! Anime: Onepiece - Boa Collectible Toy',
                'product_old_price': 50000,
                'product_price': 50000,
                'product_sell_type': 'VENTA',
                'product_state_id': 14,
                'product_state_name': 'La Guajira',
                'product_status': 'active',
                'product_subcategory_id': 20,
                'product_used': false,
                'product_visible': true,
                'product_published_at': '2019-02-26T14:21:21.436+0000',
                'seller_community_id': 2,
                'seller_community_name': 'Pragma',
                'seller_company_name': 'Pragma',
                'seller_name': 'Jairo Vendoo',
                'product_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12315/1551190927557-14127-Boa.jpg',
                'seller_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12459/1553891500908-3930-cidade-de-papel.jpg',
                'product_previous_price': null,
                'seller_company_color': '#FE782E',
                'product_manual_feature': null
            },
            {
                'product_category_id': 1,
                'product_city_id': 624,
                'product_city_name': 'Uribia',
                'product_country_id': 1,
                'product_currency': 'COP',
                'product_id': 7330,
                'product_is_low_price': false,
                'product_name': 'Funko POP Anime: One Piece Portgas D. Ace',
                'product_old_price': 50000,
                'product_price': 50000,
                'product_sell_type': 'VENTA',
                'product_state_id': 14,
                'product_state_name': 'La Guajira',
                'product_status': 'active',
                'product_subcategory_id': 20,
                'product_used': false,
                'product_visible': true,
                'product_published_at': '2019-02-26T14:20:14.303+0000',
                'seller_community_id': 2,
                'seller_community_name': 'Pragma',
                'seller_company_name': 'Pragma',
                'seller_name': 'Jairo Vendoo',
                'product_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12314/1551190861561-14127-Ace.jpg',
                'seller_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12459/1553891500908-3930-cidade-de-papel.jpg',
                'product_previous_price': null,
                'seller_company_color': '#FE782E',
                'product_manual_feature': null
            },
            {
                'product_category_id': 1,
                'product_city_id': 624,
                'product_city_name': 'Uribia',
                'product_country_id': 1,
                'product_currency': 'COP',
                'product_id': 7329,
                'product_is_low_price': false,
                'product_name': 'Funko Pop! One Piece Brook Fall Convention Exclusi',
                'product_old_price': 200000,
                'product_price': 200000,
                'product_sell_type': 'VENTA',
                'product_state_id': 14,
                'product_state_name': 'La Guajira',
                'product_status': 'active',
                'product_subcategory_id': 20,
                'product_used': false,
                'product_visible': true,
                'product_published_at': '2019-02-26T14:15:44.611+0000',
                'seller_community_id': 2,
                'seller_community_name': 'Pragma',
                'seller_company_name': 'Pragma',
                'seller_name': 'Jairo Vendoo',
                'product_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12313/1551190591767-14127-Brook.jpg',
                'seller_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12459/1553891500908-3930-cidade-de-papel.jpg',
                'product_previous_price': null,
                'seller_company_color': '#FE782E',
                'product_manual_feature': null
            },
            {
                'product_category_id': 1,
                'product_city_id': 624,
                'product_city_name': 'Uribia',
                'product_country_id': 1,
                'product_currency': 'COP',
                'product_id': 7328,
                'product_is_low_price': false,
                'product_name': 'Funko Pop Animation: One Piece - Nico Robin Collec',
                'product_old_price': 50000,
                'product_price': 50000,
                'product_sell_type': 'VENTA',
                'product_state_id': 14,
                'product_state_name': 'La Guajira',
                'product_status': 'active',
                'product_subcategory_id': 20,
                'product_used': false,
                'product_visible': true,
                'product_published_at': '2019-02-26T14:12:59.847+0000',
                'seller_community_id': 2,
                'seller_community_name': 'Pragma',
                'seller_company_name': 'Pragma',
                'seller_name': 'Jairo Vendoo',
                'product_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12312/1551190426927-14127-NicoRobin.jpg',
                'seller_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12459/1553891500908-3930-cidade-de-papel.jpg',
                'product_previous_price': null,
                'seller_company_color': '#FE782E',
                'product_manual_feature': null
            },
            {
                'product_category_id': 1,
                'product_city_id': 624,
                'product_city_name': 'Uribia',
                'product_country_id': 1,
                'product_currency': 'COP',
                'product_id': 7327,
                'product_is_low_price': false,
                'product_name': 'Funko POP Anime: One Piece Chopper Action Figure',
                'product_old_price': 50000,
                'product_price': 50000,
                'product_sell_type': 'VENTA',
                'product_state_id': 14,
                'product_state_name': 'La Guajira',
                'product_status': 'active',
                'product_subcategory_id': 20,
                'product_used': false,
                'product_visible': true,
                'product_published_at': '2019-02-26T14:10:54.698+0000',
                'seller_community_id': 2,
                'seller_community_name': 'Pragma',
                'seller_company_name': 'Pragma',
                'seller_name': 'Jairo Vendoo',
                'product_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12311/1551190301758-14127-Chopper.jpg',
                'seller_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12459/1553891500908-3930-cidade-de-papel.jpg',
                'product_previous_price': null,
                'seller_company_color': '#FE782E',
                'product_manual_feature': null
            },
            {
                'product_category_id': 1,
                'product_city_id': 624,
                'product_city_name': 'Uribia',
                'product_country_id': 1,
                'product_currency': 'COP',
                'product_id': 7326,
                'product_is_low_price': false,
                'product_name': 'Funko POP Anime: One Piece Luffy Action Figure',
                'product_old_price': 50000,
                'product_price': 50000,
                'product_sell_type': 'VENTA',
                'product_state_id': 14,
                'product_state_name': 'La Guajira',
                'product_status': 'active',
                'product_subcategory_id': 20,
                'product_used': false,
                'product_visible': true,
                'product_published_at': '2019-02-26T13:56:52.367+0000',
                'seller_community_id': 2,
                'seller_community_name': 'Pragma',
                'seller_company_name': 'Pragma',
                'seller_name': 'Jairo Vendoo',
                'product_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12310/1551189220057-14127-Luffy.jpg',
                'seller_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12459/1553891500908-3930-cidade-de-papel.jpg',
                'product_previous_price': null,
                'seller_company_color': '#FE782E',
                'product_manual_feature': null
            },
            {
                'product_category_id': 1,
                'product_city_id': 624,
                'product_city_name': 'Uribia',
                'product_country_id': 1,
                'product_currency': 'COP',
                'product_id': 7325,
                'product_is_low_price': false,
                'product_name': 'Funko Pop! Anime: One Piece - Usopp  Vinyl Figure',
                'product_old_price': 50000,
                'product_price': 50000,
                'product_sell_type': 'VENTA',
                'product_state_id': 14,
                'product_state_name': 'La Guajira',
                'product_status': 'active',
                'product_subcategory_id': 20,
                'product_used': false,
                'product_visible': true,
                'product_published_at': '2019-02-26T13:51:07.321+0000',
                'seller_community_id': 2,
                'seller_community_name': 'Pragma',
                'seller_company_name': 'Pragma',
                'seller_name': 'Jairo Vendoo',
                'product_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12309/1551189104657-14127-Usopp.jpg',
                'seller_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12459/1553891500908-3930-cidade-de-papel.jpg',
                'product_previous_price': null,
                'seller_company_color': '#FE782E',
                'product_manual_feature': null
            },
            {
                'product_category_id': 1,
                'product_city_id': 624,
                'product_city_name': 'Uribia',
                'product_country_id': 1,
                'product_currency': 'COP',
                'product_id': 7324,
                'product_is_low_price': false,
                'product_name': 'Funko Pop Anime: Onepiece - Franky Collectible Toy',
                'product_old_price': 50000,
                'product_price': 50000,
                'product_sell_type': 'VENTA',
                'product_state_id': 14,
                'product_state_name': 'La Guajira',
                'product_status': 'active',
                'product_subcategory_id': 20,
                'product_used': false,
                'product_visible': true,
                'product_published_at': '2019-02-26T13:42:25.892+0000',
                'seller_community_id': 2,
                'seller_community_name': 'Pragma',
                'seller_company_name': 'Pragma',
                'seller_name': 'Jairo Vendoo',
                'product_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12308/1551188525696-14127-Franky.jpg',
                'seller_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12459/1553891500908-3930-cidade-de-papel.jpg',
                'product_previous_price': null,
                'seller_company_color': '#FE782E',
                'product_manual_feature': null
            },
            {
                'product_category_id': 1,
                'product_city_id': 624,
                'product_city_name': 'Uribia',
                'product_country_id': 1,
                'product_currency': 'COP',
                'product_id': 7323,
                'product_is_low_price': false,
                'product_name': 'Funko Pop! Anime: Onepiece - Nami Collectible Toy',
                'product_old_price': 50000,
                'product_price': 50000,
                'product_sell_type': 'VENTA',
                'product_state_id': 14,
                'product_state_name': 'La Guajira',
                'product_status': 'active',
                'product_subcategory_id': 20,
                'product_used': false,
                'product_visible': true,
                'product_published_at': '2019-02-26T13:38:00.702+0000',
                'seller_community_id': 2,
                'seller_community_name': 'Pragma',
                'seller_company_name': 'Pragma',
                'seller_name': 'Jairo Vendoo',
                'product_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12307/1551188326292-14127-Nami.jpg',
                'seller_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12459/1553891500908-3930-cidade-de-papel.jpg',
                'product_previous_price': null,
                'seller_company_color': '#FE782E',
                'product_manual_feature': null
            },
            {
                'product_category_id': 1,
                'product_city_id': 624,
                'product_city_name': 'Uribia',
                'product_country_id': 1,
                'product_currency': 'COP',
                'product_id': 7322,
                'product_is_low_price': false,
                'product_name': 'Funko Pop! Anime: Onepiece - Zoro Collectible Toy',
                'product_old_price': 50000,
                'product_price': 50000,
                'product_sell_type': 'VENTA',
                'product_state_id': 14,
                'product_state_name': 'La Guajira',
                'product_status': 'active',
                'product_subcategory_id': 20,
                'product_used': false,
                'product_visible': true,
                'product_published_at': '2019-02-26T13:36:44.461+0000',
                'seller_community_id': 2,
                'seller_community_name': 'Pragma',
                'seller_company_name': 'Pragma',
                'seller_name': 'Jairo Vendoo',
                'product_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12306/1551188250984-14127-Zoro.jpg',
                'seller_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12459/1553891500908-3930-cidade-de-papel.jpg',
                'product_previous_price': null,
                'seller_company_color': '#FE782E',
                'product_manual_feature': null
            },
            {
                'product_category_id': 1,
                'product_city_id': 624,
                'product_city_name': 'Uribia',
                'product_country_id': 1,
                'product_currency': 'COP',
                'product_id': 7321,
                'product_is_low_price': false,
                'product_name': 'Funko Pop Animation: One Piece - Sanji (Fishman)',
                'product_old_price': 50000,
                'product_price': 50000,
                'product_sell_type': 'VENTA',
                'product_state_id': 14,
                'product_state_name': 'La Guajira',
                'product_status': 'active',
                'product_subcategory_id': 20,
                'product_used': false,
                'product_visible': true,
                'product_published_at': '2019-02-26T13:35:28.799+0000',
                'seller_community_id': 2,
                'seller_community_name': 'Pragma',
                'seller_company_name': 'Pragma',
                'seller_name': 'Jairo Vendoo',
                'product_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12305/1551188175359-14127-Sanji (Fishman).jpg',
                'seller_photo_url': 'https://s3.amazonaws.com/rotalomstg/staging/uploads/photo/file/12459/1553891500908-3930-cidade-de-papel.jpg',
                'product_previous_price': null,
                'seller_company_color': '#FE782E',
                'product_manual_feature': null
            }
        ],
        'filtros': {
            'filtroDepartamento': {
                'departamentos': [
                    {
                        'id': 14,
                        'country': null,
                        'name': 'La Guajira',
                        'quantityForFilter': 18
                    },
                    {
                        'id': 1,
                        'country': null,
                        'name': 'Antioquia',
                        'quantityForFilter': 10
                    },
                    {
                        'id': 29,
                        'country': null,
                        'name': 'Amazonas',
                        'quantityForFilter': 1
                    }
                ],
                'total': 29
            },
            'filtroCiudad': {
                'ciudades': [
                    {
                        'id': 624,
                        'createdAt': null,
                        'name': 'Uribia',
                        'updatedAt': null,
                        'state': null,
                        'orderCode': null,
                        'quantityForFilter': 17
                    },
                    {
                        'id': 19,
                        'createdAt': null,
                        'name': 'Bello',
                        'updatedAt': null,
                        'state': null,
                        'orderCode': null,
                        'quantityForFilter': 7
                    },
                    {
                        'id': 1,
                        'createdAt': null,
                        'name': 'Medellin',
                        'updatedAt': null,
                        'state': null,
                        'orderCode': null,
                        'quantityForFilter': 3
                    },
                    {
                        'id': 623,
                        'createdAt': null,
                        'name': 'San Juan Del Cesar',
                        'updatedAt': null,
                        'state': null,
                        'orderCode': null,
                        'quantityForFilter': 1
                    },
                    {
                        'id': 1052,
                        'createdAt': null,
                        'name': 'Tarapaca',
                        'updatedAt': null,
                        'state': null,
                        'orderCode': null,
                        'quantityForFilter': 1
                    }
                ],
                'total': 29
            },
            'filtroComunidad': {
                'comunidades': [
                    {
                        'id': 2,
                        'name': 'Pragma',
                        'quantityForFilter': 20
                    }
                ],
                'total': 29
            },
            'filtroTipoVenta': {
                'tiposVentas': [
                    {
                        'id': 'ALQUILA',
                        'name': 'Alquila',
                        'quantityForFilter': 1
                    },
                    {
                        'id': 'SUBASTA',
                        'name': 'Subasta',
                        'quantityForFilter': 4
                    },
                    {
                        'id': 'VENTA',
                        'name': 'Venta',
                        'quantityForFilter': 24
                    }
                ],
                'total': 29
            }
        }
    }
}
;
